/**
 * Canonical error codes surfaced to clients.
 *
 * Source of truth: `contracts/openapi.yaml` → `ErrorResponse.error.code`.
 * @internal
 */
export const ErrorCode = {
  INVALID_INPUT: 'INVALID_INPUT',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  ARTIFACT_NOT_FOUND: 'ARTIFACT_NOT_FOUND',
  WORKFLOW_NOT_FOUND: 'WORKFLOW_NOT_FOUND',
  EXECUTION_NOT_FOUND: 'EXECUTION_NOT_FOUND',
  PROVIDER_NOT_FOUND: 'PROVIDER_NOT_FOUND',
  EXPORT_NOT_FOUND: 'EXPORT_NOT_FOUND',
  INVALID_STAGE_TRANSITION: 'INVALID_STAGE_TRANSITION',
  WORKFLOW_ALREADY_RUNNING: 'WORKFLOW_ALREADY_RUNNING',
  WORKFLOW_NOT_RUNNING: 'WORKFLOW_NOT_RUNNING',
  WORKFLOW_STAGE_NOT_CLARIFICATION: 'WORKFLOW_STAGE_NOT_CLARIFICATION',
  LLM_TIMEOUT: 'LLM_TIMEOUT',
  LLM_NETWORK_ERROR: 'LLM_NETWORK_ERROR',
  LLM_CANCELLED: 'LLM_CANCELLED',
  LLM_ERROR: 'LLM_ERROR',
  ALL_MODELS_FAILED: 'ALL_MODELS_FAILED',
  COST_LIMIT_EXCEEDED: 'COST_LIMIT_EXCEEDED',
  RATE_LIMITED: 'RATE_LIMITED',
  EXPORT_NOT_READY: 'EXPORT_NOT_READY',
  EXPORT_FAILED: 'EXPORT_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
